

x-image:
   &image
   image: ${OZONE_IMAGE:-apache/ozone}:${OZONE_IMAGE_VERSION:-1.4.1}${OZONE_IMAGE_FLAVOR:-}

x-common-config:
   &common-config
   OZONE-SITE.XML_hdds.datanode.dir: "/data/hdds"
   OZONE-SITE.XML_ozone.metadata.dirs: "/data/metadata"
   OZONE-SITE.XML_ozone.om.address: "om"
   OZONE-SITE.XML_ozone.om.http-address: "om:9874"
   OZONE-SITE.XML_ozone.recon.address: "recon:9891"
   OZONE-SITE.XML_ozone.recon.db.dir: "/data/metadata/recon"
   OZONE-SITE.XML_ozone.replication: "1"
   OZONE-SITE.XML_ozone.scm.block.client.address: "scm"
   OZONE-SITE.XML_ozone.scm.client.address: "scm"
   OZONE-SITE.XML_ozone.scm.datanode.id.dir: "/data"
   OZONE-SITE.XML_ozone.scm.names: "scm"
   no_proxy: "om,recon,scm,s3g,localhost,127.0.0.1"


version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - infra

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 419430400
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:29092,PLAINTEXT_C://0.0.0.0:9093,PLAINTEXT_L://0.0.0.0:9092,
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://broker:29092,PLAINTEXT_L://localhost:9092,PLAINTEXT_C://broker:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_L:PLAINTEXT,PLAINTEXT_C:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
    networks:
      - infra

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on: 
      - broker
    ports:
      - "7777:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=broker
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker:9093
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - infra
  datanode:
    <<: *image
    ports:
        - 9864
    command: ["ozone","datanode"]
    environment:
        <<: *common-config
    volumes: 
      - dn:/data
    networks:
      infra:
  om:
    <<: *image
    ports:
        - 9874:9874
    environment:
        <<: *common-config
        ENSURE_OM_INITIALIZED: /data/metadata/om/current/VERSION
        WAITFOR: scm:9876
    command: ["ozone","om"]
    volumes:
      - om:/data
    networks:
      infra:
  scm:
    <<: *image
    ports:
        - 9876:9876
    environment:
        <<: *common-config
        ENSURE_SCM_INITIALIZED: /data/metadata/scm/current/VERSION
    command: ["ozone","scm"]
    volumes:
      - scm:/data
    networks:
      infra:
  recon:
    <<: *image
    ports:
        - 9888:9888
    environment:
        <<: *common-config
    command: ["ozone","recon"]
    networks:
      infra:
  s3g:
    <<: *image
    ports:
        - 9878:9878
    environment:
        <<: *common-config
    command: ["ozone","s3g"]
    networks:
      infra:

volumes:
  om:
  dn:
  scm:


networks:
  infra:
    driver: bridge